fix problem with CVE-2021-3520
AnacondaRecipes/lz4-c-feedstock pull request #1
Opened 2021-07-05 12:53 UTC by ekomarova

This change should help fix the problem with https://nvd.nist.gov/vuln/detail/CVE-2021-3520

2021-07-29 15:54 UTC, ekomarova commented
@remkade

2021-07-29 16:17 UTC, remkade commented
@chenghlee or @katietz It looks like upstream doesn't yet have a fix released. I'm not quite sure what our policy on this is. Do we want to maintain temporary patched version or wait until upstream releases a fix for this high severity issue?

See:
lz4/lz4#972

2021-07-29 19:20 UTC, chenghlee requested changes

2021-07-29 19:20 UTC, chenghlee commented on recipe/patches/CVE-2021-3520.patch
> +diff --git a/lib/lz4.c b/lib/lz4.c
At the top of this patch file, I would add comment and a link to the upstream issue/PR (e.g., `See: https://github.com/lz4/lz4/pull/972`) so we know where it came from and can figure out when we should drop it. 

Other than that, I think it's okay to apply this patch and rebuild the `lz4` package.

2021-07-29 20:36 UTC, chenghlee approved these changes

2021-07-29 20:46 UTC, remkade commented
Before we merge this in I want to make sure it goes through our usual build and test process. I'll hold this open until this is built and released.

@skupr-anaconda and @varlackc if you have time during your PBS Review process this is a good one to build.

2021-07-30 15:02 UTC, skupr-anaconda commented
CVE-2021-3520.patch is failed when I built the recipe.
I recommend using the format for a patch like this one https://github.com/lz4/lz4/commit/8301a21773ef61656225e264f4f06ae14462bca7.patch
I'll create a new PR with some enhancements in the recipe and comments about the patch

2021-07-30 15:10 UTC, skupr-anaconda commented
@chenghlee @remkade The new PR for review https://github.com/AnacondaRecipes/lz4-c-feedstock/pull/2

2021-08-06 12:11 UTC, skupr-anaconda commented
Merged https://github.com/AnacondaRecipes/lz4-c-feedstock/pull/2

2021-08-06 12:12 UTC, closed without merging